version: '3.7'

services:
  database_nlw:
    image: postgres
    container_name: database_nlw
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres

  app:
    image: node
    working_dir: /nlw05_chat/app
    container_name: nlw05_chat
    restart: always
    command: bash -c "npm run typeorm migration:run && npm run dev"
    ports: 
      - 3333:3333
    volumes: 
      - .:/nlw05_chat/app
    links: 
      - database_nlw
    depends_on:
      - database_nlw

volumes:
  pgdata:
